### ISSUE TITLE
[Feature Request] Support Image Upload (and potentially Embeds)

### ISSUE THREAD

**Issue by blommestein** [rfw/kobun4#1]
client.Context.SetOutputFormat('discord.embed') 
print("[message, url, filename.png]")

See:
https://discordapp.com/developers/docs/resources/channel#embed-object
https://discordapp.com/developers/docs/resources/channel#attachment-object
https://godoc.org/github.com/Rivalo/discordgo_cli#Session.ChannelFileSend
https://godoc.org/github.com/bwmarrin/discordgo#Session.ChannelMessageSendEmbed

**Comment by rfw** [comment]
supported now
