### ISSUE TITLE
[Feature Request] Expose totalMessages / totalCharacters 

### ISSUE THREAD

**Issue by blommestein** [rfw/kobun4#3]
i.e. `total_messages = client.Stats.GetUserStats(userID='whatever').TotalMessages`

```
{
    'totalMessages': 1000,
    'totalMessagesLessThan10Chars': 50,
    'totalCharacters': 10000,
}

```
Useful for quantifying (meaningful) user activity and optionally awarding it

**Comment by rfw** [comment]
This is now exposed via `Stats.GetUserChannelStats`.
