### ISSUE TITLE
[Request] .keyblade command

### ISSUE THREAD

**Issue by SvardXI** [rfw/kobun4#5]
A Keyblade lookup that displays the Keyblade by name, picture and lists the stats for each level would be handy!

**Comment by butnotexactly** [comment]
Please talk to me (jacob#2332) directly concerning khux features -- khux modules are not part of kobun itself. There are quite a few features in development including keyblade stats / equipping.

**Comment by butnotexactly** [comment]
.keyblade is now active :)

**Comment by rfw** [comment]
please don't use this issue tracker for non-platform related issues
